name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Восстанавливаем keystore из base64
      - name: Restore keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.jks

      # Собираем ПОДПИСАННЫЙ APK
      - name: Build signed Release APK
        run: |
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=release.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      # Проверка
      - name: List APK files
        run: |
          find app/build/outputs/apk -name "*.apk"

      # Загружаем APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ShortsGenerator-APK
          path: app/build/outputs/apk/release/*.apk
